# Generated by Django 5.1.dev20231109172850 on 2023-11-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="subjects",
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("accepted", "Accepted"),
                    ("finished", "Finished"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="subject",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="connect.subject",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="connect.session"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="connect.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="tutor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions_as_tutor",
                to="connect.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                choices=[
                    ("math", "Math"),
                    ("physics", "Physics"),
                    ("english", "English"),
                ],
                max_length=10,
            ),
        ),
    ]
