# Generated by Django 5.1.dev20231109172850 on 2023-11-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0002_remove_session_subjects_session_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions_as_tutor",
                to="connect.userprofile",
            ),
        ),
    ]
