# Generated by Django 5.1.dev20231109172850 on 2023-11-30 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0003_alter_session_tutor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="username",
        ),
    ]
