# Generated by Django 5.1.dev20231109172850 on 2023-11-30 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0004_rename_user_userprofile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="username",
            new_name="user",
        ),
    ]
